### ISSUE TITLE
Add a refetch command

### ISSUE THREAD

**Issue by Mm2PL** [csunday95/discord_minecraft_manager#5]
I would like for the bot to have a refetch command that would fetch the information about a Minecraft account again.
Something like: `!mc refetch <minecraft_username>` => Fetch current username using UUID.

**Comment by csunday95** [comment]
so a couple of clarifying questions on this command:

 - What's the use case?
 -  Should it also check if that UUID is registered/whitelisted?
 - Should it update the username listing within the registration if it has changed?

**Comment by Mm2PL** [comment]
- The use case: If a player changes their name, it would be nice to update what `lookupmc` returns. peepoZoom
 - yes, since otherwise there wouldn't be anything to [re]fetch
 - yes it should update the currently known player username

**Comment by csunday95** [comment]
added recheck command with either MC username or MC UUID
